### ISSUE TITLE
[Dev-Nightly] Rest of config is swiping after /woo register

### ISSUE THREAD

**Issue by HappyHarm** [WooMinecraft/WooMinecraft#60]
When you use /woo register to key the key for the first time it saves the key to the config but swipes the rest of the config http://prntscr.com/9s20s2

**Comment by TekkitCommando** [comment]
I looked at the code and I know exactly what's do it.

**Comment by TekkitCommando** [comment]
I will try to get on a PC in 15 if I can and fix it

**Comment by TekkitCommando** [comment]
I will have it fixed today after i'm out of class.

**Comment by HappyHarm** [comment]
See that you did some commits in the dev-nightly with the config? Is the issue solved?

**Comment by TekkitCommando** [comment]
@HappyHarm should be I gotta jar download in releases section.

**Comment by HappyHarm** [comment]
Need to compile it with java 7 for myself. Will do that somewhere this afternoon.

**Comment by JayWood** [comment]
I've ran the command numerous times this morning, cannot duplicate.

**Comment by TekkitCommando** [comment]
@Jay Wood I fixed it in the commit I made a few days ago

**Comment by HappyHarm** [comment]
Just tried the newest build and it looks like it's still not fixed

**Comment by TekkitCommando** [comment]
@HappyHarm it's weird, for some reason people that used the alpha builds say this still happens (mmuziek tried so many times that I guess it flushed the cached data and started working correctly for him) I am trying to find a Java command that deletes cached data or build info for earlier jars

**Comment by TekkitCommando** [comment]
It may be the fact that the code says that 'key' only instead of pointing at 'WooMinecraft.web.key' it's a location statement and I'm sure I changed it to be 'WooMinecraft.web.key' and @JayWood changed the code in the register command back to just 'key' but I'm not sure why

**Comment by TekkitCommando** [comment]
I am working on a few things and will push them to dev nightly later today

**Comment by HappyHarm** [comment]
Ok then, thanks for the quick response :)

**Comment by JayWood** [comment]
@TekkitCommando WooMinecraft.web.key was the nested config, and the config is no longer nested.

**Comment by TekkitCommando** [comment]
@JayWood Ah ok, that's how I know the data is cached on my server then cuz it is still nested for me even with the new jar.

**Comment by JayWood** [comment]
@TekkitCommando I believe the issue may be with `saveConfig` here:

![](https://i.gyazo.com/7121fa0317ea3ec54b58b3cf44c29908.png)

Maybe we have to get the entire config, and then write it?

**Comment by TekkitCommando** [comment]
@JayWood I don't see why you would, it worked fine before. plugin.saveConfig() should work fine and setting the key shouldn't effect the other config options. I don't see you having to do plugin.getConfig().saveConfig(); but I mean you could try

**Comment by JayWood** [comment]
@TekkitCommando I can't do anything until after work today, it's currently 9AM, so nothing from me until 5PM [ GMT -5 ]

Admittedly I didn't test that command **my bad** I'm used to having a full QA team at my side :smile: If you have time give it a go, if not I'll have a look after work.

**Comment by TekkitCommando** [comment]
@JayWood I don't think that .getConfig().saveConfig() will even work actually xD I will give it a try :P Oh yeah a job, I need to get one of those things. Maybe I will find a job in Python development or PHP/Java after I finish my classes lol

**Comment by TekkitCommando** [comment]
@JayWood I tested my theory of using getConfig and saveConfig and it was a fail :/

**Comment by JayWood** [comment]
@TekkitCommando @HappyHarm is this still a thing?

**Comment by TekkitCommando** [comment]
I am not sure, my computer is not working correctly, I bought some parts to fix it and then I will get the latest jar and test this. Sorry for the inactivity, like I said I bought some parts so maybe I will have the JDK installed today and be back to code again :D

**Comment by HappyHarm** [comment]
Idk my hosting got cleared a week ago and didn't got time to re-setup everything. Maybe I can test it this evening, if I forgot renember me :P

**Comment by HappyHarm** [comment]
Yep issue is still here. Sorry for the delay, forgot it as expected :P

**Comment by TekkitCommando** [comment]
I will restructure the config code today if i get the time :)

**Comment by TekkitCommando** [comment]
@JayWood This was fixed right?

**Comment by JayWood** [comment]
No, purely added a todo to look into it.

**Comment by TekkitCommando** [comment]
@JayWood 0-0 Ok I will fix it real quick.

**Comment by JayWood** [comment]
@TekkitCommando - this is now fixed.  Though has yet to be merged into master.

**Comment by TekkitCommando** [comment]
@JayWood I ended up changing the code that should have fixed it but my freakin git would not work for the life of me. :P

**Comment by JayWood** [comment]
@TekkitCommando if that happens again it'd be great if you can at least gist up the file and link it in the task, I'd be glad to copy it in.  It's better than letting tasks go stagnant for months I'd say.

**Comment by TekkitCommando** [comment]
No it was like 3 days ago. My git was working a couple weeks ago.

**Comment by TekkitCommando** [comment]
It's working again now.
